# View the docs https://docs.anyscale.com/reference/service-api#serviceconfig.

name: deploy-llama-3-1-8b

# Requries building an image from the included Dockerfile and pushing it
# to an azure container registry. Update the image_uri field below with the URI of your
# image in ACR.
image_uri: <acr-repository-name>.azurecr.io/<image-name>:<tag>

# When empty, Anyscale will auto-select the instance types. You can also specify
# minimum and maximum resources.
compute_config:
#   head_node:
#     instance_type: m5.2xlarge
#   worker_nodes:
#     - instance_type: m5.16xlarge
#       min_nodes: 0
#       max_nodes: 100
#     - instance_type: m7a.24xlarge
#       min_nodes: 0
#       max_nodes: 100
#       market_type: PREFER_SPOT # Defaults to ON_DEMAND
#     - instance_type: g4dn.2xlarge
#       min_nodes: 0
#       max_nodes: 100
#       market_type: PREFER_SPOT # Defaults to ON_DEMAND
#  auto_select_worker_config: true

# Path to a local directory or a remote URI to a .zip file (S3, GS, HTTP) that
# will be the working directory for the job. The files in the directory will be
# automatically uploaded to the job environment in Anyscale.
working_dir: .

# When empty, this uses the default Anyscale Cloud in your organization.
cloud:

# Specify the Ray Serve app to deploy.
applications:
- import_path: serve_llama_3_1_8b:app
